name: Screener

on:
  workflow_dispatch:

jobs:
  scr:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Instalacia kniznic
        run: pip install --quiet yfinance pandas numpy
      - name: Screener
        run: python screener.py
